trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define variables
  buildConfiguration: 'Release'
  azureServiceConnection: 'reactjsConnection'
  appName: 'Dev-reacApp123'
  resourceGroupName: 'dev-reactApp123'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x' # Specify the Node.js version
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install NPM dependencies'

  - script: |
      npm run build
    displayName: 'Build React app'

  - task: CopyFiles@2
    inputs:
      contents: 'build/**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy build output to artifact staging directory'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'drop'
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish build artifacts'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      appName: '$(appName)'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      runtimeStack: 'NODE|14-lts' # Specify the runtime stack
    displayName: 'Deploy to Azure Web App'

