name: Build and Deploy React App to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Verify installed dependencies
        run: |
          $output = Invoke-Expression "npm ls @mui/base --json"
          $package = $output | ConvertFrom-Json
          if (!$package.dependencies.'@mui/base') {
            npm install @mui/base@latest
          }
      - name: Build React app
        run: npm run build
        env:
          CI: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./build-artifacts

      - name: Debug artifact path
        run: |
          echo "Current working directory: $PWD"
          echo "Contents of build-artifacts directory:"
          ls ./build-artifacts

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ vars.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ vars.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ vars.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Check permissions
        run: |
          $pwd = Resolve-Path -Path .
          $srcPath = "$pwd/build-artifacts"
          Get-Acl $srcPath | Format-List
        shell: pwsh
        env:
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        run: |
          $pwd = Resolve-Path -Path .
          $srcPath = "$pwd/build-artifacts"
          az webapp deploy --resource-group 'webapp1' --name 'reactjswebApp' --src-path $srcPath --type static
        shell: pwsh
        env:
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
